### ISSUE TITLE
Monolog v2 support

### ISSUE THREAD

**Issue by acelaya** [wshafer/psr11-monolog#10]
This project looks great! Congratulations.

However I see there has been no changes on the past 2 years, and it does not support monolog v2.

Is there any chance to get support for it?

**Comment by wshafer** [comment]
Yes. We will be updating shortly.  Thanks for the reminder

**Comment by wshafer** [comment]
Version [3.0.0](https://github.com/wshafer/psr11-monolog/releases/tag/3.0.0) released with support for Monolog 2
