### ISSUE TITLE
New tag for master

### ISSUE THREAD

**Issue by jaapio** [wshafer/psr11-monolog#6]
Hi @wshafer,

Thanks for this pretty library. I was wondering if you are still working on a new version or if a new tag can be created based on the latest version in master.

We are using you package in our new zf2 module https://github.com/polderknowledge/log-module. The missing tag doesn't allow us to create a v2 tag for a our module. 
Please let me know when you need any help before creating the tag. We would be pleased to help you out.

**Comment by wshafer** [comment]
Hi @jaapio 

Thanks for the report.  Tag 2.1.0 released.

Westin

**Comment by jaapio** [comment]
Thanks for the quick response
